### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by mlocati**
See individial commits for an explanation that's better than "Improvements" 😉

About the composer.json: the `name` included in this PR is currently `mesuva/msv_cloudflare_turnstile`.
The trailing `msv_cloudflare_turnstile` must be the same as the package handle.

What about the leading `mesuva` part? Is it ok? Or do you usually use another "namespace"?

### CODE REVIEW

**Comment by Mesuva** [comment]
These are all great little improvements, I'll make sure they find their way to the marketplace version.

No issue with the mesuva namespace, I don't use another one for composer related purposes.

**Comment by mlocati** [comment]
> No issue with the mesuva namespace, I don't use another one for composer related purposes.

What about [this one](https://packagist.org/packages/mesuva/msv_table)?

**Comment by Mesuva** [comment]
I think I'm misunderstanding your question - I'm saying I've never used anything other than 'mesuva' namespace in packagist, so what you've put in composer.json should be consistent with what I've done in the past.

**Comment by mlocati** [comment]
Whoops, sorry! Yep my fault

**Comment by mlocati** [comment]
One thing that's missing are git tags (packagist uses them to handle versions).
So, for example, you should push a tag like `1.0.1` for the current version

**Comment by mlocati** [comment]
@Mesuva also, this repo should be submitted to [packagist](https://packagist.org/packages/mesuva/), of course 😉

**Comment by Mesuva** [comment]
Both have been done (updated to v1.0.2)

**Pull request merged**
